language: php
sudo: false
dist: trusty

env:
  global:
    - JTRACKER_ENVIRONMENT="travis"

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - bin/jtracker test run
